defaults:
  - base_llama
  - _self_

name: qwen-2.5-72b
model: Qwen/Qwen2.5-72B
instruct: False

module: model
encoders: layers

layers:
  - 0
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 79

task_layers:
  cities_loc: 22
  med_indications: 20
  defs: 8