hydra:
  run:
    dir: outputs/hydra_logs/probes/prompt/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: ???
  - _self_

datasets: ["city_locations", "medical_indications", "defs"]
layers: ${model.layers}
device: null
variation: "default"

output_dir: "outputs/probes/zero_shot/${model.name}"

question_type: multichoice

random_seed: 42
batch_size: 12
limit_batches: -1  # number of batches to run the analysis on; -1 means all
max_context_statements: 100

enum_list: ["a", "b", "c"]

# Which perturbation condition to run
#   - 0: baseline, no added context
#   - 1: use datasets/{dataset}_synthetic.csv with in_train == 1
#   - 2: use datasets/{dataset}_fictional.csv with in_train == 1
#   - 3: use datasets/{dataset}_fictional.csv with in_train == 1 & correct == 1
perturbation_type: 0